fix: init for BlueStacks5 x64 Hyper-V
SimonShi1994/Princess-connection-farm pull request #501
Opened 2023-01-22 11:56 UTC by sgpublic

+ 修复：init 指令未使用 emulator_ports 配置
+ 新增：支持 BlueStacks 5 Nougat x64 运行在 Hyper-V 环境下时读取端口号

2023-01-25 13:34 UTC, TheAutumnOfRice requested changes
感谢贡献！如果需要合并的话，还有一些小细节希望有时间能稍微修改一下。
1. 涉及到config的修改需要在docs里的INI文件配置解读.md中新增对应的条目，并且在main_new.py中。此外，需要在info命令中添加相应的提示，见main_new.py#L329  ShowAutoConsole()
2. 见main_new.py批注。
3. 更新时希望能修改main_new.py开头的版本号字符串， readme.md开头的版本号以及readme.md末尾的更新记录，格式仿照之前即可。

2023-01-26 05:47 UTC, sgpublic commented
是我考虑不周，提交了新的commit，这样可以吗

2023-01-27 13:32 UTC, TheAutumnOfRice requested changes
感谢修改！
但是我注意到你有的地方写了蓝蝶，有的地方写了蓝叠。
也许你应该统一名称为蓝叠，可能会更好一些？

2023-01-27 13:34 UTC, sgpublic commented
> 感谢修改！ 但是我注意到你有的地方写了蓝蝶，有的地方写了蓝叠。 也许你应该统一名称为蓝叠，可能会更好一些？

啊这个哈哈哈，是我打字没注意打错了，感谢提醒

2023-01-28 02:31 UTC, merged